// import { defineConfig } from 'vite'
// import react from '@vitejs/plugin-react'

// // https://vite.dev/config/
// export default defineConfig({
//   plugins: [react()],
// })
// vite.config.ts
// import { defineConfig } from "vite";
// import react from "@vitejs/plugin-react";

// export default defineConfig({
//   plugins: [react()],
//   build: {
//     outDir: "dist",
//     lib: {
//       // just give the relative path directly
//       entry: "src/widget.tsx",
//       name: "ChatbotWidget",
//       fileName: () => "chatbot-widget.js",
//       formats: ["iife"],
//     },
//   },
// });
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import fs from "fs/promises";
import path from "path";

export default defineConfig({
  plugins: [
    react(),
    // plugin to generate an index.html into outDir after lib build
    {
      name: "generate-index-for-widget",
      apply: "build",
      configResolved(resolvedConfig) {
        // remember outDir for writeBundle
        this._outDir = resolvedConfig.build.outDir || "dist";
      },
      async writeBundle(options, bundle) {
        try {
          const outDir = this._outDir || "dist";
          // Find the JS and CSS files generated by the build
          const files = Object.values(bundle || {});
          const jsFile = files.find(
            f => f.type === "chunk" && /\.js$/.test(f.fileName) && /chatbot-widget/i.test(f.fileName)
          )?.fileName
            // fallback: any .js chunk if specific name not matched
            || files.find(f => f.type === "chunk" && /\.js$/.test(f.fileName))?.fileName;

          const cssFile = files.find(f => f.type === "asset" && /\.css$/.test(f.fileName))?.fileName;

          // If no js found, try common filename fallback
          const finalJs = jsFile || "chatbot-widget.js";
          const finalCss = cssFile || null;

          // Construct index.html content
          const html = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width,initial-scale=1" />
    <title>Chatbot Widget Demo</title>
    ${finalCss ? `<link rel="stylesheet" href="./${finalCss}">` : ""}
    <style>
      /* minimal container for demo */
      body { margin:0; font-family: system-ui, sans-serif; display:flex; align-items:center; justify-content:center; height:100vh; }
      #chatbot-root { width: 360px; height: 640px; border: 1px solid #ddd; border-radius: 12px; overflow:hidden; box-shadow: 0 6px 18px rgba(0,0,0,0.08); }
    </style>
  </head>
  <body>
    <div id="chatbot-root"></div>
    <script>
      // If your widget expects to auto-mount to #chatbot-root, this is ready.
      // Otherwise, you can manually initialize ChatbotWidget from the bundled global.
    </script>
    <script src="./${finalJs}"></script>
  </body>
</html>
`;

          // ensure outDir exists (should already) then write index.html
          const indexPath = path.resolve(process.cwd(), outDir, "index.html");
          await fs.mkdir(path.dirname(indexPath), { recursive: true });
          await fs.writeFile(indexPath, html, "utf8");
          // optional: log (Vite will show plugin logs in build output)
          // eslint-disable-next-line no-console
          console.log(`[generate-index-for-widget] wrote ${indexPath}`);
        } catch (err) {
          // eslint-disable-next-line no-console
          console.error("[generate-index-for-widget] failed to write index.html:", err);
        }
      },
    },
  ],
  build: {
    outDir: "dist",
    emptyOutDir: true,
    lib: {
      // relative path to your entry
      entry: "src/widget.tsx",
      name: "ChatbotWidget",
      fileName: () => "chatbot-widget.js",
      formats: ["iife"],
    },
    // keep sourcemap if you want
    // sourcemap: true,
    rollupOptions: {
      // If you need to externalize deps, add them here.
      // external: [], 
    },
  },
  server: {
    allowedHosts: [
      ".ngrok-free.app",
      "localhost",
    ],
  },
});
  